### PR TITLE
Re-implement scrobbling time logic

### LINKED ISSUE #26: Multiple track scrobbling
There is a bug (incorrect behavior) in WAIL.

WAIL can scrobble track multiple times if you or Android will pause the track WAIL can scrobble it, and then, scrobble it again if it will be continued

### PR DESCRIPTION
**Pull request by ilya-murzinov**
@artem-zinnatullin, a review would be great.

Fixes #26

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Scheduled :)
7 июня 2015 г. 9:01 PM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

File: wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java [hunk 1]
```diff
@@ -172,25 +172,42 @@ protected Void doInBackground(Void... params) {
...
-                                if (trackDurationInPercents >= WAILSettings.getMinTrackDurationInPercents(getApplicationContext())) {
-                                    Loggi.w("Track playing duration in millis == " + trackPlayingDurationInMillis + ", in % == " + trackDurationInPercents + " >= min track duration in % == " + WAILSettings.getMinTrackDurationInPercents(getApplicationContext()));
+                            Loggi.w("Track playing duration in millis == " + trackPlayingDurationInMillis
+                                    + " >= min track duration in millis == "
+                                    + (WAILSettings.getMinTrackDurationInSeconds(getApplicationContext()) * 1000));
+
+                            long capturedDuration = mLastCapturedTrackInfo.getTrack().getDuration();
+                            // Some players set duration in seconds, some in milliseconds
+                            // If duration is greater then 30000 we assume that it measured in milliseconds
+                            long duration =
```
Comment (artem-zinnatullin) [inline wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java]: May be it would be better to move this to some method? For example into: `getDuration()` itself? And rename `getDuration()` to `getDurationMillis()`?

**Comment by artem-zinnatullin** [comment]
LGTM!

File: wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java (hunk 1 above)
Comment (ilya-murzinov) [inline wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java]: Agreed!

**Comment by ilya-murzinov** [comment]
Found a bug, will fix :)
